openapi: 3.0.0
info:
  title: Sample API
  version: 0.1.9
servers:
- url: /
paths:
  /:
    get:
      operationId: listPayments
      parameters:
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: skip
        required: false
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: sort
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPaymentsResponse'
          description: A JSON array of payments
      summary: Returns a list of payments.
      tags:
      - payments
    put:
      operationId: savePayment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
        required: true
      responses:
        "201":
          description: A payment object was created
        "204":
          description: A payment object was updated
      summary: Persist payment
      tags:
      - payments
components:
  schemas:
    ListPaymentsResponse:
      example:
        data:
        - reference: reference
          date: 2000-01-23T04:56:07.000+00:00
          scheme: visa
          provider: provider
          raw: ""
          id: id
          type: pay-in
          value:
            amount: 0
            asset: asset
          status: status
        - reference: reference
          date: 2000-01-23T04:56:07.000+00:00
          scheme: visa
          provider: provider
          raw: ""
          id: id
          type: pay-in
          value:
            amount: 0
            asset: asset
          status: status
      properties:
        data:
          items:
            $ref: '#/components/schemas/Payment'
          type: array
      required:
      - data
      type: object
    Payment:
      example:
        reference: reference
        date: 2000-01-23T04:56:07.000+00:00
        scheme: visa
        provider: provider
        raw: ""
        id: id
        type: pay-in
        value:
          amount: 0
          asset: asset
        status: status
      properties:
        provider:
          type: string
        reference:
          type: string
        scheme:
          enum:
          - visa
          - mastercard
          - apple pay
          - google pay
          - sepa debit
          - sepa credit
          - sepa
          - a2a
          - ach debit
          - ach
          - rtp
          - other
          type: string
        status:
          type: string
        type:
          enum:
          - pay-in
          - payout
          - other
          type: string
        id:
          type: string
        value:
          $ref: '#/components/schemas/Payment_value'
        date:
          format: date-time
          type: string
        raw:
          nullable: true
      required:
      - date
      - id
      - provider
      - scheme
      - status
      - type
      - value
      type: object
    Payment_value:
      example:
        amount: 0
        asset: asset
      properties:
        amount:
          type: integer
        asset:
          type: string
      required:
      - amount
      - asset
      type: object
